version: '3.1'

services:
### Nginx Server Container #############################
  nginx:
      build: ./build/nginx
      privileged: true
      ports:
        - "801:801"
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      links:
        - "php"
        - "php56"
      volumes:
        # Nginx默认配置文件
        - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
        # 配置虚拟主机
        - ./vhost/:/etc/nginx/conf.d/
        # SSL密钥Key存放路径
        - ./ssl-key/:/etc/nginx/cert/
        # Nginx访问路径
        - ./www/:/var/www/
        # Nginx访问路径
        - ./logs/nginx/:/var/log/nginx/

### PHP Container #############################
  php:
      build:
        context: ./build/php
        dockerfile: Dockerfile
        args:
          - INSTALL_XDEBUG=${INSTALL_XDEBUG}
          - PHP_VERSION=${PHP_VERSION}
      privileged: true
      ports:
        - "9007:9000"
      links:
        - "mysql"
        - "redis"
      volumes:
        # 映射访问地址
        - ./www/:/var/www/
        # ssh 私人密钥
        - ./ssh-key/:/root/.ssh/
        # git 钩子，git版本有更新时 pull代码
        - ./logs/webhook/:/var/log/webhook/
  php56:
      build: ./build/php5.6
      privileged: true
      ports:
        - "9056:9000"
      links:
        - "mysql"
        - "mongo"
      volumes:
        - ./www/:/var/www/
### MYSQL Container #############################
  mysql:
      build:
        context: ./build/mysql
        dockerfile: Dockerfile
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      restart: always
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      privileged: true
      ports:
        - "${MYSQL_HOST_PORT}:3306"
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./data/backup_mysql/:/data/backup/db
        - ./logs/mysql/:/var/log/mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}

### PostgreSQL Container ####################################

  postgres:
      build: ./build/postgresql
      ports:
        - "5432:5432"
      volumes:
        - ./data/postgresql:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=default
        - POSTGRES_USER=default
        - POSTGRES_PASSWORD=kfkdock

### Redis Container #############################

  redis:
      build: ./build/redis
      privileged: true
      ports:
        - "6379:6379"
      volumes:
        - ./data/redis:/data
        - ./logs/redis:/var/log/redis

### Mongo Container #############################

  mongo:
      build: ./build/mongo
      privileged: true
      ports:
        - "27017:27017"
      volumes:
        - ./data/mongo:/data/db

### Node Container #############################

  node:
      build: ./build/node
      privileged: true
      ports:
        - "8080:8080"
      volumes:
        - ./www/:/var/www/
networks:
  lnmp: